package config

import (
	"text/template"
)

var nginxTemplate = template.Must(template.New("config").Parse(
	`# DO NOT EDIT
# File generated by cloudanchor

server {
    listen 80;
    listen [::]:80;
    server_name {{.domains}};
    return 301 https://{{.domain}};
}

server {
    listen 443 ssl;
    listen [::]:443;
    server_name {{.domains}};
    proxy_pass http://127.0.0.1:{{.port}};
}
`,
))
